<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>LyDev - Extend Setting</title>
	<link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css" rel="stylesheet">
</head>

{% if redirect != null %}
	<script>
		location.href = "{{redirect}}";
	</script>
{% endif %}

<style>
	::-webkit-scrollbar-track-piece {

		background-color: #f8f8f8;

	}

	::-webkit-scrollbar {

		width: 9px;

		height: 9px;

	}

	::-webkit-scrollbar-thumb {

		background-color: #9f9f9f;

		background-clip: padding-box;

		min-height: 28px;

	}

	::-webkit-scrollbar-thumb:hover {

		background-color: #bbb;

	}
</style>

<body style="background-color: #c8c8c8;" {% if body !=null %} {% for eve in body._evr %}
	{{eve.trigger}}="{{eve.function}}" {% endfor %} {% endif %}>

	<div class="container">
		<br />
		<div class="card">
			<div class="card-body">
				{% if forms != null %}
				<form>
					<div id="render_form">
						{% for lab in forms %}
						<div class="form-group">
							{% if lab['_lab'] == 'input' %}
							{% if lab['label'] %}
							<label for="exampleInputEmail1">{{ lab['label'] }}</label>
							{% endif %}

							<input type="{{lab['type']}}" placeholder="{{lab['hint']}}" value="{{lab['value']}}"
								id="{{lab['id']}}" class="form-control">

							{% if lab['note'] %}
							<small class="for99m-text text-muted">{{ lab['note'] }}</small>
							{% endif %}

							{% elseif lab['_lab'] == 'select' %}

							{% if lab['label'] %}
							<label for="exampleInputEmail1">{{ lab['label'] }}</label>
							{% endif %}

							<select class="custom-select" id="{{lab['id']}}" ckr="{{lab['_ckr']}}">
								{% for opt in lab['options'] %}
								<option value="{{opt}}">{{opt}}</option>
								{% endfor %}
							</select>

							{% elseif lab['_lab'] == 'button' %}
							<button type="{{lab['type']}}" class="btn btn-primary btn-block {{lab['class']}}" {% for evs
								in lab['_evr'] %} {{evs['trigger']}}="{{evs['function']}}" {% endfor
								%}>{{lab['text']}}</button>
							{% endif %}

						</div>
						{% endfor %}
					</div>
				</form>
				{% else %}
				<div>
					<strong>当前拓展无任何自定义配置支持。[ ERR: EMPTY ]</strong>
				</div>
				{% endif %}
			</div>
		</div>
	</div>


	<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.5.3/js/bootstrap.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/layui-layer@1.0.9/dist/layer.min.js"></script>

	<script src="/@dev/extres/@{{extname}}-Dev-Package.js"></script>
</body>

</html>
